### ISSUE TITLE
How to use this tool for testing 

### ISSUE THREAD

**Issue by pranjal-b** [tamboto2000/facebook#1]

**Comment by tamboto2000** [comment]
Hello Pranjal, this library is still under alpha stage and might be not
stable, but I'am actively working on it. As of I'm writing this e-mail to
you, the current features in this library is to get basic profile info
including user ID, full name, alter name, cover photo, and profile picture,
if you have request for adding more features, please let me know. The
documentation should be accessed on
pkg.go.dev/github.com/tamboto2000/facebook, I'm not updated the
documentation yet, I will inform you when the documentation is updated

**Comment by tamboto2000** [comment]
> 
> 
> _No description provided._

The documentation is updated, see https://pkg.go.dev/github.com/tamboto2000/facebook@v1.0.0-alpha
